### ISSUE TITLE
Deploy from github service hook

### ISSUE THREAD

**Issue by johnkors** [WindowsAzure/windowsazure.github.io#3]
Hi guys, did not know where to put this feature request, so please feel free to relay or show me where to post it if in the wrong place:

A neat feature of github is the service hook bit. When pushing to a github master branch, I would like to have a service hook that deploys my latest commit on the github master branch into the azure master branch. Similar to what Appharbor does today:

https://github.com/blog/961-deploy-to-appharbor-from-github

**Comment by ogail** [comment]
Thanks for the suggestion I'll direct that for someone who can help.

**Comment by VishalRJoshi** [comment]
Hi John, yes this is indeed on our radar. We will be looking into this soon!!

**Comment by davidebbo** [comment]
@johnkors  For future reference, the correct project for this is https://github.com/projectkudu/kudu
